const MESSAGES = {
    USER_COMMAND: 'USER_COMMAND',
    SPEAK_RESPONSE: 'SPEAK_RESPONSE',
    GET_PAGE_STATE: 'GET_PAGE_STATE',
    GET_PAGE_CONTEXT: 'GET_PAGE_CONTEXT',
    EXECUTE_ACTIONS: 'EXECUTE_ACTIONS',
    ACTIONS_RESULT: 'ACTIONS_RESULT',
    PAGE_LOADED: 'PAGE_LOADED',
    START_MIC: 'START_MIC',
    STOP_MIC: 'STOP_MIC',
    TOGGLE_MIC: 'TOGGLE_MIC',
    THINKING_START: 'THINKING_START',
    THINKING_STOP: 'THINKING_STOP',
    MIC_STATE_CHANGED: 'MIC_STATE_CHANGED'
};

const CONFIG = {
    GEMINI_TIMEOUT_MS: 15000,
    ACTION_DELAY_MS: 400,
    NARRATION_DEBOUNCE_MS: 2000,
    MAX_NARRATION_ITEMS: 5
};
